export const FEROUTES = {
  HOMEPAGE: "/tugas-akhir", // Ini yang dikiri tiga duplikatnya
  STUDENT_HOMEPAGE: "/tugas-akhir/mahasiswa",
  STUDENT_LAB_FREE: "/tugas-akhir/mahasiswa/bebas-lab",
  STUDENT_FINAL_EXAM_PROPOSAL: "/tugas-akhir/mahasiswa/tugas-akhir",
  STUDENT_FINAL_EXAM_PROPOSAL_HISTORY: "/tugas-akhir/mahasiswa/tugas-akhir/riwayat",
  STUDENT_NEW_FINAL_EXAM_PROPOSAL: "/tugas-akhir/mahasiswa/tugas-akhir/buat",
  STUDENT_PROFILE: "/tugas-akhir/mahasiswa/profil",
  STUDENT_SEMINAR: "/tugas-akhir/mahasiswa/seminar",
  STUDENT_SEMINAR_HISTORY: "/tugas-akhir/mahasiswa/seminar/riwayat",
  STUDENT_TRIAL_PERMIT: "/tugas-akhir/mahasiswa/ujian-sidang",
  STUDENT_GUIDANCE: "/tugas-akhir/mahasiswa/bimbingan",
  FIRST_VICE_DEAN_HOMEPAGE: "/tugas-akhir/wakil-dekan-1",
  FIRST_VICE_DEAN_APPROVAL: "/tugas-akhir/wakil-dekan-1/persetujuan",
  FIRST_VICE_DEAN_APPROVAL_MENTOR_AND_EXAMINERS: "/tugas-akhir/wakil-dekan-1/persetujuan/sk-pembimbing-dan-penguji",
  FIRST_VICE_DEAN_APPROVAL_MENTOR_AND_EXAMINERS_MORE: "/tugas-akhir/wakil-dekan-1/persetujuan/sk-pembimbing-dan-penguji/nim",
  FIRST_VICE_DEAN_APPROVAL_TRIAL_PERMIT: "/tugas-akhir/wakil-dekan-1/persetujuan/ujian-sidang",
  FIRST_VICE_DEAN_APPROVAL_TRIAL_PERMIT_MORE: "/tugas-akhir/wakil-dekan-1/persetujuan/ujian-sidang/nim",
  STUDY_PROGRAM_ADMIN_HOMEPAGE: "/tugas-akhir/admin-program-studi",
  STUDY_PROGRAM_ADMIN_APPROVAL: "/tugas-akhir/admin-program-studi/persetujuan",
  STUDY_PROGRAM_ADMIN_APPROVAL_PROPOSAL: "/tugas-akhir/admin-program-studi/persetujuan/judul-penelitian",
  STUDY_PROGRAM_ADMIN_APPROVAL_PROPOSAL_APPLICATION: "/tugas-akhir/admin-program-studi/persetujuan/judul-penelitian/permohonan-judul-penelitian",
  STUDY_PROGRAM_ADMIN_APPROVAL_PROPOSAL_APPLICATION_HISTORY: "/tugas-akhir/admin-program-studi/persetujuan/judul-penelitian/permohonan-judul-penelitian/riwayat",
  // STUDY_PROGRAM_ADMIN_APPROVAL_PROPOSAL_APPLICATION_DETAILS: "/tugas-akhir/admin-program-studi/persetujuan/judul-penelitian/permohonan-judul-penelitian/nim",
  STUDY_PROGRAM_ADMIN_APPROVAL_PROPOSAL_SUBMISSION: "/tugas-akhir/admin-program-studi/persetujuan/judul-penelitian/pengajuan-judul-penelitian",
  STUDY_PROGRAM_ADMIN_APPROVAL_PROPOSAL_SUBMISSION_HISTORY: "/tugas-akhir/admin-program-studi/persetujuan/judul-penelitian/pengajuan-judul-penelitian/riwayat",
  STUDY_PROGRAM_ADMIN_APPROVAL_EXAMINERS_TEAM: "/tugas-akhir/admin-program-studi/persetujuan/penyusunan-tim-penguji",
};
